[build]
  publish = "dist"
  command = "npm run build"

[functions]
  directory = "netlify/functions"

# API redirects first
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# SPA routing - this should be the ONLY redirect for HTML pages
# The key is that Netlify will serve existing files first, then fall back to this redirect
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for service worker
[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "no-cache"
    Service-Worker-Allowed = "/"

# Headers for assets folder (Vite puts built files here)
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

# Headers for CSS files
[[headers]]
  for = "*.css"
  [headers.values]
    Content-Type = "text/css"
    Cache-Control = "public, max-age=31536000"

# Headers for JavaScript files  
[[headers]]
  for = "*.js"
  [headers.values]
    Content-Type = "application/javascript"
    Cache-Control = "public, max-age=31536000"

# Global security headers (applied after specific headers)
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[dev]
  command = "npm run dev"
  port = 8080
  publish = "dist"
